"""
================================================================================
FINWISE AI – AGENT SCHEMAS & DATA CONTRACTS
Author: Zaid (Intelligent Agent & Web Search Lead)
================================================================================
Defines stable Pydantic schemas for the Intelligent Agent output, ensuring
seamless typed consumption by Step 3 (Anshuman's FastAPI Backend & Orchestrator).
================================================================================
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Structured web citation derived strictly from real web search results."""
    title: str = Field(description="Title of the web page or document")
    source: str = Field(description="Source name or domain")
    url: str = Field(description="Direct URL to the retrieved web source")
    snippet: str = Field(description="Relevant excerpt or summary from the web source")


class AdvisoryMarketIntelligence(BaseModel):
    """Real-time market context gathered from live web search."""
    market_summary: str = Field(description="Summary of current market conditions derived dynamically from search")
    web_citations: List[Citation] = Field(default_factory=list, description="List of actual citations retrieved from the live web")


class AdvisoryResponse(BaseModel):
    """
    Standardized advisory report output model for Step 3 Orchestrator.
    Conforms strictly to docs/API_CONTRACTS.md Section 1.1 and 2.2.
    """
    status: str = Field(default="success", description="Status of the advisory generation")
    risk_score: float = Field(description="Authoritative crisp risk score from Aman's Fuzzy Logic Evaluator (0-100)")
    risk_category: str = Field(description="Authoritative risk category from Aman's Fuzzy Logic Evaluator")
    asset_allocation: Dict[str, float] = Field(description="Deterministic portfolio allocation percentages summing to 100%")
    budget_metrics: Optional[Dict[str, Any]] = Field(default=None, description="50/30/20 budget metrics and investable surplus")
    debt_metrics: Optional[Dict[str, Any]] = Field(default=None, description="DTI ratio and debt analysis")
    emergency_fund_metrics: Optional[Dict[str, Any]] = Field(default=None, description="Emergency buffer coverage and shortfall")
    grounded_rules_referenced: List[str] = Field(default_factory=list, description="IDs of triggered expert system production rules")
    market_summary: str = Field(description="Dynamic macroeconomic overview from live search")
    web_citations: List[Citation] = Field(default_factory=list, description="Verified live search citations")
    citations: List[Citation] = Field(default_factory=list, description="Alias for web_citations for backward compatibility")
    markdown_report: str = Field(description="Comprehensive advisory report generated by the LLM grounded in real facts")


class ChatResponse(BaseModel):
    """
    Standardized response for interactive conversational follow-up questions.
    Conforms strictly to docs/API_CONTRACTS.md Section 1.2 and 2.2.
    """
    status: str = Field(default="success", description="Status of the chat response")
    reply: str = Field(description="Natural language explanation grounded in active financial plan rules")
    grounded_rules_referenced: List[str] = Field(default_factory=list, description="Rule IDs directly referenced or applicable")
    sources_used: List[Citation] = Field(default_factory=list, description="Live web sources retrieved to answer the question, if any")
